language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: projet-catho-front
  api_key:
    secure: gz3Bu9vO+GB0zIYgO2lu5QXw1vgXwlrqYcSh4vW0UVyZCStWpjaR+jduPftJEUEkoeLlNSUcoBdxhLy+TbJdjU3xUrZGu9cvhe2cZxu8o5nVzGeZC+B8mgjEkJtj+mcEnCXy9TmN+WNX03bNHSFoMhaVl1QirYtzjTvocdEa3IKvZU9+helpJ19l8u2F9LhV1tRJ5XhGbi5Gmkp53phSScsEotSmVO80LrKGkAcGFRUWoFPY9qYFVW8KqHzDIIDyeFOdhmmlSD4SaZh70MnyvWQfwmEYxrcHItepAdT2HR5x+q8HAO3Nvx2iGMItN0FRs4RLxhKeYMJVG/O+XYmBgLBrUOLRWR3QfbN0JiiZF/XRTKZifhQUKASHbMFV1TBmPeuwsG9fG64c4YcmoFs3Sqs1nEnijStHtcuHOJU0v8wWzTB77GB+5mrDmgFSE8vQexxWP5KUPNeRez6WEzAwc1eL6gfM0zxL7F/XkDJKsDvOH84mDY30/40D6Na9niSI1QopIm2Cgp5M4NaQVgUDEcwPIiUkQyZJo85vhYDdThgVdIelN3olYNEZBwjNL/xsjnjvZGcR5k76zvcxpBd/y86WeMuPh2QXmipdYDIVZYCjw62zFrPK0+pAPr1EPCxEkTWe8eCa0nWqQ0+2OYjKMUcw3C/naP/zgM4AE1KDS1M=
cache:
  directories:
  - node_modules
script:
- npm run build
