language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: projet-catho-front
  api_key:
    secure: Gswn3C5gkPJQRyCthlZrs2S/P2bSnsJRYHUmb32r5G89+DPbSs/dKYvFULOb0xw7pMZ/Uzhx+50bwVe4cHc8f8K6HBWIii+8Pl3CholLnL/M/3BSyPE9akXBv89FlPmUvtI4ebfwEbnhJNPf2Lccync2/724zXgvEZG8jTRX6lJfDTBQDFeR4+lDEKv4H5UyT5wRW6wNS4N/gQ4bxDZ/HdO8cMjS7UkUxcaLEupMkSQwrpY4mNqfD7iajCpis+TgroUN9OlAhI+FqLOJ0jT0AlNW/bKiWCKSTCmlVvBzm8USgRDZYGbyyPAYNzhHIyZww30mS3EBNFwUsiV4wijuAg+NThnvwtd3hhqtJAS+1zS4C20JhowGlj9QVPcVi4baMjXaAYGHbs6tVkhsoK1akMbvhqJaxQmfDxfDoyI9kRZJH5fGPxApenyXbqxqf86EAoRlVBwXaSXlS4/KnnMUruFVT7y1GHpd0ufNugB1RZVrxYdpqYsg3JjIqa/QFV0YeQ860GwnHoKBysWua1nUXUDADeaesbOnu7+h0eAEBWhjWDy3NTD3E10yZhzXtZkMv69+PIATzr9BbZU/ZweZRq6Aiz99wJgYZ9KCuQBXe46NojtwSiZsJ+pdAMec6Xb/dtuGZvoRM7mojzoDe/55qRmLwSoiPeU9LGfMHd+KTbI=
cache:
  directories:
  - node_modules
script:
- npm run build
